### PR TITLE
Layout fixes

### PR DESCRIPTION
**Pull request by blackbox87**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Fixes various layout issues on devices using Android 4.1
- Correct the vector drawable used after [#3271](https://github.com/TeamNewPipe/NewPipe/pull/3271)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by blackbox87** [comment]
@friendlyanon @TobiGr Is there a reason this pull request didn't get merged into v0.19.8?

Currently you're using stuff like layout_marginStart, but because that attribute doesn't exist in API 16 you don't get the expected look. Android Studio would normally warn you about this and fail to compile the app, but for some reason NewPipe Legacy is setup to ignore these warnings.

**Comment by MD77MD** [comment]
is this related to my problem https://github.com/TeamNewPipe/NewPipe-legacy/issues/18#issuecomment-679415946

**Review by TobiGr — APPROVED** [review]
Are these changes necessary, because Android <= 4.4 does not know the `...Start` and `...End` layout params? If this is the case, I'd like to draw your attention to https://github.com/TeamNewPipe/NewPipe/pull/3488 which removes the hard-coded left and right layout params for better RTL support.

So if this is the problem, this looks good to me. However @friendlyanon takes care of the legacy repository and should therefore merge / review this PR.

**Comment by blackbox87** [comment]
> Are these changes necessary, because Android <= 4.4 does not know the `...Start` and `...End` layout params?

Yes. Here's a quick example of what NewPipe Legacy looks like before and after applying the changes.
newpipe_compare

> If this is the case, I'd like to draw your attention to TeamNewPipe/NewPipe#3488 which removes the hard-coded left and right layout params for better RTL support.

That pull request will be a problem for NewPipe Legacy because they've replaced the left/right attributes with start/end and they've also used [getLayoutDirection()](https://developer.android.com/reference/android/content/res/Configuration#getLayoutDirection()) and android:supportsRtl, which are only available in Android 4.2 or newer.

**Comment by blackbox87** [comment]
@TobiGr By the way, one of the fixes in this pull request [should also be copied to NewPipe](https://github.com/TeamNewPipe/NewPipe/blob/ea43b28f740d99c326e8a94315b8e64a7368af1f/app/src/main/res/layout/list_radio_icon_item.xml#L18).

This is another of them warnings that would normally prevent the app from being compiled, since ic_play doesn't exist.

**Comment by blackbox87** [comment]
@TobiGr By the way, one of the fixes in this pull request [should also be copied to NewPipe](https://github.com/TeamNewPipe/NewPipe/blob/ea43b28f740d99c326e8a94315b8e64a7368af1f/app/src/main/res/layout/list_radio_icon_item.xml#L18).

Android Studio would normally warn you about ic_play not existing and not compile the app, but because NewPipe is setup to ignore most warnings issues like this keep slipping through.

**Comment by blackbox87** [comment]
@TobiGr By the way, one of the fixes in this pull request [should also be copied to NewPipe](https://github.com/TeamNewPipe/NewPipe/blob/ea43b28f740d99c326e8a94315b8e64a7368af1f/app/src/main/res/layout/list_radio_icon_item.xml#L18).

Issues like this keep slipping through because of how NewPipe is configured to ignore most warnings. In this case the drawable doesn't exist, which isn't a critical issue, but [trying to use functions that don't exist](https://github.com/TeamNewPipe/NewPipe-legacy/issues/38) on your minimum supported API level is.

**Comment by blackbox87** [comment]
@TobiGr By the way, one of the fixes in this pull request [should also be copied to NewPipe](https://github.com/TeamNewPipe/NewPipe/blob/ea43b28f740d99c326e8a94315b8e64a7368af1f/app/src/main/res/layout/list_radio_icon_item.xml#L18).

Issues like this keep slipping through because of how NewPipe is configured to ignore most warnings. In this case the drawable doesn't exist, which isn't a critical issue, but it is when you're [trying to use methods that don't exist](https://github.com/TeamNewPipe/NewPipe-legacy/issues/38) on your minimum API level.

**Pull request merged**
